[package]
name = "find"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.3"
chrono = "0.4"
clap = { version = "4.4", features = ["derive"] }
encoding_rs = "0.8"
log = "0.4"
simple_logger = "4.2"
indicatif = "0.17"
rayon = "1.8"
once_cell = "1.21.1"
